import class1.prelim_drag as drag1
from classes.aircraft_2 import Aircraft
from lookups.consts import *

def taxi_frac(ac : Aircraft) -> float:
    
def takeoff_frac(ac : Aircraft) -> float:
    ...
def climb_frac(ac : Aircraft) -> float:
    ...
def cruise_frac(ac : Aircraft) -> float:
    ...
def descent_frac(ac : Aircraft) -> float:
    ...
def loiter_frac(ac : Aircraft) -> float:
    ...
def landing_frac(ac : Aircraft) -> float:
    ...


def class1_mass(ac : Aircraft) -> float:
    ...